### ISSUE TITLE
Drop official support / updates for debian 9

### ISSUE THREAD

**Issue by AlistairB** [haskell/docker-haskell#48]
Just when I was ready for some quiet time around here.. ;)

So it seems as of cabal-install 3.6.2.0 it [no longer supports debian 9](https://discourse.haskell.org/t/ann-cabal-3-4-1-0-cabal-install-3-4-1-0-cabal-3-6-2-0-cabal-install-3-6-2-0/3412/4?u=alistairb).

We could keep updating deb 9, but leave cabal on 3.6.0.0 or we could drop support. My inclination is to drop support as it could be confusing having differing versions of cabal in stretch vs buster.

The docs state `Additionally, we support the two most versions of Debian (stable and oldstable) as variants, with the most recent being the default if not specified.`. `oldstable` is `buster` at this point with `bullseye` being released. Although cabal, ghc and possibly stack do not support deb 11 yet.

Anyway, I propose to remove deb 9 from the listed images and no longer update them. Then add deb 11 once haskell ecosystem supports it.

@psftw No rush on this one, but what do you think?

**Comment by psftw** [comment]
Supporting the two most recent versions of Debian is a goal of sorts, but if we are limited by upstream packages then we don't have a choice. What you propose sounds good to me, with the addition that we should call it out in the docs. Essentially 8.10.7 & 9.0.1 would be the last versions to support a `-stretch` variant due to `cabal>=3.6.2.0` not supporting it. If we can only support Debian 10 in the short term, and add 11 later, that's the best we can do.

**Comment by AlistairB** [comment]
> we should call it out in the docs

Sounds good. I'll update the following. Noting that for now we only support buster / oldstable for now. We can probably also drop the note at this point.

> Additionally, we support the two most versions of Debian (stable and oldstable) as variants, with the most recent being the default if not specified.

> Note: haskell:8.8.3 was updated from Debian Stretch to Buster, so you will need to specify haskell:8.8.3-stretch to stick with Stretch in this particular case.

**Comment by AlistairB** [comment]
All updated :tada:
